### ISSUE TITLE
Slack private token?

### ISSUE THREAD

**Issue by ghost** [voidabhi/cricinfo-slackbot#5]
Aloha,

The `cricinfoslack.py` file seems to expose a private slack token. See https://labs.detectify.com/2016/04/28/slack-bot-token-leakage-exposing-business-critical-information/ for more information about this.

**Comment by voidabhi** [comment]
Thanks for reporting.

Although i had created a test team for that, but got your point.

**Comment by voidabhi** [comment]
Fixed c11536bb5f5d0b2343da335bc6efbba8498e5449
